base_model = "openai/gpt-oss-20b"
name = "GPT-OSS 20B TEE"
reasoning = false
tool_call = false
structured_output = false

[cost]
input = 0.04
output = 0.15
cache_read = 0.02

[limit]
input = 131_072
output = 8_192
