name = "Llama 3.1 405B"
description = "Llama 3.1 405B hosted by IONOS in Berlin, Germany. Zero data retention."
family = "llama"
release_date = "2026-09-10"
last_updated = "2026-09-10"
attachment = false
reasoning = false
tool_call = true
structured_output = false
open_weights = true

[cost]
input = 2.0265
output = 2.0265

[limit]
context = 131_072
input = 131_072
output = 8_192

[modalities]
input = ["text"]
output = ["text"]
