base_model = "perplexity/sonar-deep-research"
name = "Perplexity Deep Research"
reasoning = false
structured_output = false

[cost]
input = 3.4
output = 13.6
cache_read = 1.7

[limit]
input = 128_000
output = 115_200
