base_model = "perplexity/sonar-reasoning-pro"
name = "Perplexity Reasoning Pro"
attachment = false
structured_output = false
reasoning_options = []

[cost]
input = 2
output = 8
cache_read = 1

[limit]
input = 128_000
output = 115_200

[modalities]
input = ["text"]
