name = "Hy4 preview"
description = "A next-generation productivity model with significantly enhanced Agent and complex task execution capabilities."
family = "Hy"
release_date = "2026-08-28"
last_updated = "2026-08-28"
attachment = false
reasoning = true
temperature = true
tool_call = true
open_weights = true

[limit]
context = 1_024_000
output = 64_000

[modalities]
input = ["text"]
output = ["text"]
