name = "Claude 4 Opus"
description = "Claude 4 Opus by Anthropic. The premium version of the new Claude models. A new generation model with improved capabilities, especially on programming and development."
family = "claude-opus"
release_date = "2025-08-05"
last_updated = "2025-08-05"
attachment = true
reasoning = false
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 15
output = 75
cache_read = 1.5

[limit]
context = 200_000
input = 200_000
output = 32_000

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]
