name = "DeepSeek V4 Flash Latest"
description = "This model always redirects to the latest model in the DeepSeek V4 Flash family."
family = "deepseek"
release_date = "2026-08-01"
last_updated = "2026-08-01"
attachment = false
reasoning = true
temperature = true
tool_call = true
structured_output = true
open_weights = false

[[reasoning_options]]
type = "effort"
values = ["none", "low", "high", "max"]

[cost]
input = 0.06706
output = 0.13412
cache_read = 0.013412

[limit]
context = 1_024_000
output = 384_000

[modalities]
input = ["text"]
output = ["text"]
